### ISSUE TITLE
dirty_update_counter issues

### ISSUE THREAD

**Issue by mpope9** [klarna/mnesia_eleveldb#15] opened 2018-06-17 16:18 UTC
Hi, I have issues updating a counter.

```
iex(5)> :mnesia.create_table(:metrics, [{:leveldb_copies, [node()]}, {:attributes, [:metric, :counter, :last_updated_timestamp]}, {:type, :set}])

iex(6)> :mnesia.dirty_update_counter(:metrics, "collisions", 1)
** (exit) {:aborted, {:combine_error, :metrics, :update_counter}}
    (mnesia) mnesia.erl:351: :mnesia.abort/1

```
Not shown, creating schema and starting mnesia.

Is this a mistake on my end?

**Comment by mikpe** [comment] 2018-06-17 16:28
Thanks for reporting this issue, I'll look into it tomorrow.

**Comment by mikpe** [comment] 2018-06-19 09:00
I can reproduce, however the errors also occurs if one changes the table type to e.g. disc_only_copies.

The problem is that dirty_update_counter/2 and /3 require that the records are of exactly size 3 (including table name), but your records are of size 4.  Remove the last_updated_timestamp attribute and mnesia will accept this call.

I hope this helps.

Closing as this was not a bug in mnesia_eleveldb.

**Closed by mikpe** 2018-06-19 09:00 UTC
